# config.py
REDDIT_CLIENT_ID = '3-527IlAw0R6_yYwL9d-iA'
REDDIT_CLIENT_SECRET = '4MBu6aglW3eO1vKKGGNSavYSkCDBUQ'
REDDIT_USER_AGENT = 'AIProject'
REDDIT_USERNAME = 'MintyCookie139'
REDDIT_PASSWORD = 'helloyouguy123'
